--
-- PostgreSQL database dump
--

\restrict 53xJxdZMBvPWr4R5CUifwUaY3Kbd0PbMixM6i0DDuGV9H84gPIRULPW6NlqeIwR

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: classe; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.classe (
    id integer NOT NULL,
    nom character varying(255) NOT NULL,
    annee character varying(9) NOT NULL,
    is_archived boolean NOT NULL,
    filiere_id integer NOT NULL
);


--
-- Name: classe_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.classe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: classe_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.classe_user (
    classe_id integer NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


--
-- Name: emargement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.emargement (
    id integer NOT NULL,
    statut character varying(255) NOT NULL,
    heure_signature timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    etudiant_id integer NOT NULL,
    session_id integer NOT NULL
);


--
-- Name: emargement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.emargement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emargement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: filiere; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.filiere (
    id integer NOT NULL,
    nom character varying(255) NOT NULL,
    description character varying(255) DEFAULT NULL::character varying,
    niveau character varying(50) NOT NULL,
    is_archived boolean NOT NULL
);


--
-- Name: filiere_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.filiere ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.filiere_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: justificatif; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.justificatif (
    id integer NOT NULL,
    url_fichier character varying(255) NOT NULL,
    statut character varying(50) NOT NULL,
    date_soumission date NOT NULL,
    emargement_id integer NOT NULL,
    motif_refus text,
    motif_absence character varying(255) NOT NULL
);


--
-- Name: justificatif_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.justificatif ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.justificatif_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matiere; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.matiere (
    id integer NOT NULL,
    nom character varying(255) NOT NULL,
    is_archived boolean NOT NULL
);


--
-- Name: matiere_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.matiere ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matiere_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messenger_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


--
-- Name: messenger_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session_cours; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.session_cours (
    id integer NOT NULL,
    date_cours date NOT NULL,
    heure_debut time(0) without time zone NOT NULL,
    heure_fin time(0) without time zone NOT NULL,
    tolerance_retard integer,
    emplacement character varying(255) NOT NULL,
    classe_id integer NOT NULL,
    formateur_id integer NOT NULL,
    matiere_id integer NOT NULL,
    qr_code_token character varying(255) DEFAULT NULL::character varying,
    qr_token_expires_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


--
-- Name: session_cours_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.session_cours ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.session_cours_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    email character varying(180) NOT NULL,
    roles json NOT NULL,
    password character varying(255) NOT NULL,
    nom character varying(100) NOT NULL,
    prenom character varying(100) NOT NULL,
    is_archived boolean NOT NULL,
    must_change_password boolean DEFAULT false NOT NULL
);


--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: classe classe_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classe
    ADD CONSTRAINT classe_pkey PRIMARY KEY (id);


--
-- Name: classe_user classe_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classe_user
    ADD CONSTRAINT classe_user_pkey PRIMARY KEY (classe_id, user_id);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: emargement emargement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emargement
    ADD CONSTRAINT emargement_pkey PRIMARY KEY (id);


--
-- Name: filiere filiere_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.filiere
    ADD CONSTRAINT filiere_pkey PRIMARY KEY (id);


--
-- Name: justificatif justificatif_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.justificatif
    ADD CONSTRAINT justificatif_pkey PRIMARY KEY (id);


--
-- Name: matiere matiere_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matiere
    ADD CONSTRAINT matiere_pkey PRIMARY KEY (id);


--
-- Name: messenger_messages messenger_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);


--
-- Name: session_cours session_cours_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_cours
    ADD CONSTRAINT session_cours_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: idx_26b7344a155d8f51; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_26b7344a155d8f51 ON public.session_cours USING btree (formateur_id);


--
-- Name: idx_26b7344a8f5ea509; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_26b7344a8f5ea509 ON public.session_cours USING btree (classe_id);


--
-- Name: idx_26b7344af46cd258; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_26b7344af46cd258 ON public.session_cours USING btree (matiere_id);


--
-- Name: idx_71bbb250613fecdf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_71bbb250613fecdf ON public.emargement USING btree (session_id);


--
-- Name: idx_71bbb250ddeab1a3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_71bbb250ddeab1a3 ON public.emargement USING btree (etudiant_id);


--
-- Name: idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON public.messenger_messages USING btree (queue_name, available_at, delivered_at, id);


--
-- Name: idx_8f87bf96180aa129; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_8f87bf96180aa129 ON public.classe USING btree (filiere_id);


--
-- Name: idx_90d3c5dc80bd4dcf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_90d3c5dc80bd4dcf ON public.justificatif USING btree (emargement_id);


--
-- Name: idx_9380a3af8f5ea509; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_9380a3af8f5ea509 ON public.classe_user USING btree (classe_id);


--
-- Name: idx_9380a3afa76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_9380a3afa76ed395 ON public.classe_user USING btree (user_id);


--
-- Name: uniq_emargement_etudiant_session; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_emargement_etudiant_session ON public.emargement USING btree (etudiant_id, session_id);


--
-- Name: uniq_identifier_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_identifier_email ON public."user" USING btree (email);


--
-- Name: uniq_session_qr_code_token; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_session_qr_code_token ON public.session_cours USING btree (qr_code_token);


--
-- Name: session_cours fk_26b7344a155d8f51; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_cours
    ADD CONSTRAINT fk_26b7344a155d8f51 FOREIGN KEY (formateur_id) REFERENCES public."user"(id);


--
-- Name: session_cours fk_26b7344a8f5ea509; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_cours
    ADD CONSTRAINT fk_26b7344a8f5ea509 FOREIGN KEY (classe_id) REFERENCES public.classe(id);


--
-- Name: session_cours fk_26b7344af46cd258; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_cours
    ADD CONSTRAINT fk_26b7344af46cd258 FOREIGN KEY (matiere_id) REFERENCES public.matiere(id);


--
-- Name: emargement fk_71bbb250613fecdf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emargement
    ADD CONSTRAINT fk_71bbb250613fecdf FOREIGN KEY (session_id) REFERENCES public.session_cours(id);


--
-- Name: emargement fk_71bbb250ddeab1a3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emargement
    ADD CONSTRAINT fk_71bbb250ddeab1a3 FOREIGN KEY (etudiant_id) REFERENCES public."user"(id);


--
-- Name: classe fk_8f87bf96180aa129; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classe
    ADD CONSTRAINT fk_8f87bf96180aa129 FOREIGN KEY (filiere_id) REFERENCES public.filiere(id);


--
-- Name: justificatif fk_90d3c5dc80bd4dcf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.justificatif
    ADD CONSTRAINT fk_90d3c5dc80bd4dcf FOREIGN KEY (emargement_id) REFERENCES public.emargement(id);


--
-- Name: classe_user fk_9380a3af8f5ea509; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classe_user
    ADD CONSTRAINT fk_9380a3af8f5ea509 FOREIGN KEY (classe_id) REFERENCES public.classe(id) ON DELETE CASCADE;


--
-- Name: classe_user fk_9380a3afa76ed395; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classe_user
    ADD CONSTRAINT fk_9380a3afa76ed395 FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 53xJxdZMBvPWr4R5CUifwUaY3Kbd0PbMixM6i0DDuGV9H84gPIRULPW6NlqeIwR

