<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260713115653 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE justificatif (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url_fichier VARCHAR(255) NOT NULL, statut VARCHAR(50) NOT NULL, date_soumission DATE NOT NULL, emargement_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_90D3C5DC80BD4DCF ON justificatif (emargement_id)');
        $this->addSql('ALTER TABLE justificatif ADD CONSTRAINT FK_90D3C5DC80BD4DCF FOREIGN KEY (emargement_id) REFERENCES emargement (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE justificatif DROP CONSTRAINT FK_90D3C5DC80BD4DCF');
        $this->addSql('DROP TABLE justificatif');
    }
}
