<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260708134422 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE matiere (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, is_archived BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE session_cours (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_cours DATE NOT NULL, heure_debut TIME(0) WITHOUT TIME ZONE NOT NULL, heure_fin TIME(0) WITHOUT TIME ZONE NOT NULL, tolerance_retard INT DEFAULT NULL, emplacement VARCHAR(255) NOT NULL, classe_id INT NOT NULL, formateur_id INT NOT NULL, matiere_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_26B7344A8F5EA509 ON session_cours (classe_id)');
        $this->addSql('CREATE INDEX IDX_26B7344A155D8F51 ON session_cours (formateur_id)');
        $this->addSql('CREATE INDEX IDX_26B7344AF46CD258 ON session_cours (matiere_id)');
        $this->addSql('ALTER TABLE session_cours ADD CONSTRAINT FK_26B7344A8F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session_cours ADD CONSTRAINT FK_26B7344A155D8F51 FOREIGN KEY (formateur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session_cours ADD CONSTRAINT FK_26B7344AF46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE session_cours DROP CONSTRAINT FK_26B7344A8F5EA509');
        $this->addSql('ALTER TABLE session_cours DROP CONSTRAINT FK_26B7344A155D8F51');
        $this->addSql('ALTER TABLE session_cours DROP CONSTRAINT FK_26B7344AF46CD258');
        $this->addSql('DROP TABLE matiere');
        $this->addSql('DROP TABLE session_cours');
    }
}
