<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260709141210 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE emargement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, statut VARCHAR(255) NOT NULL, heure_signature TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, etudiant_id INT NOT NULL, session_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_71BBB250DDEAB1A3 ON emargement (etudiant_id)');
        $this->addSql('CREATE INDEX IDX_71BBB250613FECDF ON emargement (session_id)');
        $this->addSql('ALTER TABLE emargement ADD CONSTRAINT FK_71BBB250DDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE emargement ADD CONSTRAINT FK_71BBB250613FECDF FOREIGN KEY (session_id) REFERENCES session_cours (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE emargement DROP CONSTRAINT FK_71BBB250DDEAB1A3');
        $this->addSql('ALTER TABLE emargement DROP CONSTRAINT FK_71BBB250613FECDF');
        $this->addSql('DROP TABLE emargement');
    }
}
